#Merge all dynamic resource packs from all mods that use this library into a single pack
merge_dynamic_packs = true
#Prevents map texture from being upladed to GPU when only map markers have changed.Could increase performance
lazy_map_upload = true

